n_classes: 2
modality: music
# 'music', 'speech', or 'video'
which: openl3
# 'mfcc', 'msd' or 'openl3' for music, 'slow_fast' for video, 'hubert' for speech
voice: false
drop_non_significant: true
repetitions: 10
folds: 5