targets_list: 
  - [Girls/women, Boys/men]
cls_dict:
# to perform only target classification set "cls_dict: {}"
# and comment out the rest of the keys
modality: music
# 'music', 'speech', or 'video'
which_embeddings:
  - mfcc
# 'mfcc', 'msd', 'openl3' for music, 'slow_fast' for video, 'hubert' for speech
voice_list:
  - false
  - true
drop_non_significant: true
filmed: false
max_epochs: 200
repetitions: 5 
folds: 5
# random seed is not set in k-fold, so 5x5 "folds"
